# Generated by Django 5.0.4 on 2024-04-20 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_category",
                    models.CharField(
                        max_length=150, verbose_name="Наименование категории"
                    ),
                ),
                (
                    "description_category",
                    models.TextField(verbose_name="Описание категории"),
                ),
            ],
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name_product", "category_product"],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.AddField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                blank=True,
                help_text="Введите дату загрузки продукта",
                null=True,
                verbose_name="Дата создания",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="price_long",
            field=models.IntegerField(
                blank=True,
                help_text="Введите цену за продукт",
                null=True,
                verbose_name="Цена продукта",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                blank=True,
                help_text="Введите дату последнего изменения",
                null=True,
                verbose_name="Дата последнего изменения",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description_product",
            field=models.TextField(
                help_text="Введите описание продукта", verbose_name="Описание продукта"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="name_product",
            field=models.CharField(
                help_text="Введите название продукта",
                max_length=150,
                verbose_name="Наименование продукта",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="picture_product",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите изображение продукта",
                null=True,
                upload_to="catalog/media",
                verbose_name="Изображение продукта",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category_product",
            field=models.ForeignKey(
                blank=True,
                help_text="Введите категорию продукта",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="catalog.category",
                verbose_name="Категория продукта",
            ),
        ),
    ]
