# Generated by Django 5.0.4 on 2024-04-20 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_category_alter_product_options_product_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="manufactured_at",
            field=models.DateField(
                blank=True,
                help_text="Введите дата производства продукта",
                null=True,
                verbose_name="Дата производства продукта",
            ),
        ),
    ]
