# Generated by Django 5.0.4 on 2024-05-01 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_product_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GetProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="заголовок")),
                ("content", models.TextField(verbose_name="содержание")),
                (
                    "picture",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="catalog/media",
                        verbose_name="Изображение продукта",
                    ),
                ),
                (
                    "created_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата создания"
                    ),
                ),
            ],
            options={
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
    ]
