# Generated by Django 5.0.4 on 2024-05-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_getproduct"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GetProduct",
        ),
        migrations.AlterField(
            model_name="product",
            name="created_at",
            field=models.DateField(
                auto_now_add=True,
                help_text="Введите дату загрузки продукта",
                null=True,
                verbose_name="Дата создания",
            ),
        ),
    ]
