# Generated by Django 5.0.4 on 2024-05-01 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_product_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="updated_at",
            field=models.DateField(
                blank=True,
                help_text="Введите дату последнего изменения",
                null=True,
                verbose_name="Дата последнего изменения",
            ),
        ),
    ]
