# Generated by Django 5.0.4 on 2024-05-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_alter_product_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_available",
            field=models.BooleanField(
                default=True,
                help_text="Укажите, доступен ли продукт",
                verbose_name="Доступен",
            ),
        ),
    ]
