# Generated by Django 4.2.2 on 2024-05-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_product_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="user",
            new_name="author",
        ),
    ]
